<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <Version>0.0.0</Version>
    <BaseOutputPath>$(MSBuildThisFileDirectory)Bin/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
